packages:
  - 'packages/*'

overrides:
  esbuild: 0.19.11
  caniuse-lite: 1.0.30001778
  babel-plugin-jsx-dom-expressions: 0.39.6

catalog:
  axios: ^1.16.1
  vite: ^8.0.8
  unplugin-dts: ^1.0.0
  vite-plugin-solid: ^2.11.8
  rollup-plugin-node-externals: ^8.0.1
  unocss: ^66.3.3
  "@unocss/preset-icons": ^66.3.3
  "@unocss/reset": ^66.3.3
  solid-js: ^1.9.12
  execa: ^9.6.1
  "@gi-tcg/gts-runtime": ^0.6.7
  "@gi-tcg/gtsc": ^0.6.7
  "@gi-tcg/gts-transpiler": ^0.6.7
  "@gi-tcg/unplugin-gts": ^0.6.7

patchedDependencies:
  ohm-js@17.1.0: patches/ohm-js@17.1.0.patch
  puppeteer-screen-recorder@3.0.6: patches/puppeteer-screen-recorder@3.0.6.patch

minimumReleaseAgeExclude:
  - '@gi-tcg/*'
  - espolar

allowBuilds:
  '@bufbuild/buf': true
  '@ffmpeg-installer/darwin-arm64': true
  '@ffmpeg-installer/linux-x64': true
  '@nestjs/core': true
  '@prisma/engines': true
  '@swc/core': true
  '@vscode/vsce-sign': true
  core-js: true
  esbuild: true
  keytar: true
  prisma: true
  puppeteer: true
